### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/GPMLj.jl#16]
Why `GPMLj.jl`, not just `GPML.jl`?

**Comment by sharanry** [comment]
Apparently, Julia Package naming guidelines requires it to be at least 5 letters long.

**Comment by willtebbutt** [comment]
Was this discussed in a PR somewhere? Or is this just from the documentation?

**Comment by sharanry** [comment]
There was a pretty long discussion on this [here](https://github.com/JuliaRegistries/General/pull/7661).

**Comment by theogf** [comment]
How about `GauPro` ?  (my love for puns has no limits)

**Comment by devmotion** [comment]
I've read through the discussion but GMPLj still doesn't feel right to me. The suffix `.jl` already indicates that it is a Julia package, so it feels weird to just append a `j` to GPML to get something with 5 characters.

Apart from that, I think one might consider renaming at least the organization GMPLj since the name of the organization is not restricted by any Julia conventions or guidelines. The name GPMLj seems very focused on this package, so maybe the organization could be renamed to something more general such as GPJ (similar to MLJ) or JuliaGP (similar to JuliaDiffEq). Personally I would prefer JuliaGP since it is more explicit and easier to understand (GPJ feels very cryptic IMO).

**Comment by theogf** [comment]
+1 for JuliaGP !

**Comment by devmotion** [comment]
It seems the goal of this package is to implement Julia interfaces to GPflow and GPyTorch, so maybe one could keep these in seperate packages named GPflow.jl and GPyTorch.jl? Possibly having separate packages could also reduce the number of dependencies, in particular users that would want to work with GPyTorch wouldn't have to install GPflow and TensorFlow.

**Comment by yebai** [comment]
No problem, happy to change the name of the org account once a consensus is reached. 

Regarding the name of the package, I was thinking about removing the redundant `.jl` suffix, i.e. `GPMLj` instead of `GPMLj`.jl`. The main purpose of the GPflow wrapper is to get a working GP implementation first and can be separated into its own package if needed. While the overall goal of `GPMLj` is to have a GPML equivalent but leveraging modern Julia features and automatic differentiation. That said, if a good name can be found, I'm happy to rename the package too. 

Regarding GPyTorch, I no longer think it is necessary to wrap around the python library to get PyTorch's GPU acceleration, since the [`Torch.jl`](https://github.com/TuringLang/Torch.jl) the library is almost functional.

**Comment by willtebbutt** [comment]
> Regarding the name of the package, I was thinking about removing the redundant .jl suffix,

Please, no. Literally _every_ Julia package in existence conforms to the convention that `.jl` is used as a suffix.

I can definitely get on board with calling the organisation JuliaGP though, since there is plenty of precedent for that, and it's pretty clear what the name means.

**Comment by cpfiffer** [comment]
Another +1 for JuliaGP.

**Comment by yebai** [comment]
Unfortunately, the user name [`JuliaGP`](https://github.com/JuliaGP) is already occupied. What about `JuliaGPML`?

**Comment by willtebbutt** [comment]
`JuliaGaussianProcesses`? `Bit verbose, but it is certainly clear about what it's about. The issue with `JuliaGPML` is against the acronym and the fact that it sounds ML-specific.

**Comment by devmotion** [comment]
Ah that's unfortunate. I think JuliaGaussianProcesses is good. It shouldn't matter that it's more verbose since people don't have to enter the full path of the repo when they install packages from the registry.

**Comment by cpfiffer** [comment]
JuliaGPs is open.

**Comment by yebai** [comment]
I'm happy with `JuliaGaussianProcesses`. On the other hand, `GPJulia` is open - we can go for that given if we want something more compact.

**Comment by yebai** [comment]
Done - renamed org name to `JuliaGaussianProcesses`.
